### PR TITLE
fix: try to add ARCHFLAGS

### PR DESCRIPTION
**Pull request by henryiii**
Just a guess that this might work

### CODE REVIEW

**Review by JorjMcKie — COMMENTED** [review]
Thanks for submitting this.
It does not work however:
```
/Users/travis/.travis/functions: line 109: export: `-arch': not a valid identifier
/Users/travis/.travis/functions: line 109: export: `x86_64 prefix=/usr/local install && cd .. && pip3 install --upgrade pip': not a valid identifier
```
As specified, those parameters are fed into a `make` command, which simply knows nothing of such a parameter.
There is the cibuildwheel parameter `CIBW_ARCHS_MACOS`, which I already used before. I also tried out to put it before the `CIBW_BEFORE_BUILD` command.
Didn't help either.

**Comment by henryiii** [comment]
Since Travis builds on the PR, I can just try a few things and see what works. If it passes eventually, if you can point me at a wheel I can try loading it on my M1.

**Comment by henryiii** [comment]
And if we find something that works, I'll likely update https://github.com/joerick/cibuildwheel/issues/618 with the info from what we find.

**Comment by JorjMcKie** [comment]
The ARCHFLAGS specification is somehow invalid and causes the MAC OSX build to crash, here is the [logfile](https://travis-ci.org/github/JorjMcKie/py-mupdf/jobs/762494993).
In Linux this parameter is ignored and a - at first sight - potentially valid wheel is produced, [logfile](https://travis-ci.org/github/JorjMcKie/py-mupdf/jobs/762494992).

The whole run produces 2 wheels if successful. OSX can be found [here](https://github.com/pymupdf/PyMuPDF-wheels/tree/osx-extra), and Linux [here](https://github.com/pymupdf/PyMuPDF-wheels/tree/linux-extra).

**Comment by henryiii** [comment]
This is invalid on Linux and nothing is needed there anyway, it's emulated, not cross compiled. It should be removed from the Linux entry.

I'll try to look into the macOS error in a couple of hours.

**Comment by JorjMcKie** [comment]
ok

**Pull request merged**
