### PR TITLE
Add linux aarch64 wheel support

### PR DESCRIPTION
**Pull request by odidev**
Added linux aarch64 wheel support.
Related to [#1018](https://github.com/pymupdf/PyMuPDF/issues/1018). @JorjMcKie Could you plaese review this PR?

### CODE REVIEW

**Comment by JorjMcKie** [comment]
I don't think this would work. According to cibuildwheel documentation I created this special-purpose YAML file: 
[travis-extra.yml.zip](https://github.com/JorjMcKie/py-mupdf/files/6342271/travis-extra.yml.zip)

**Comment by odidev** [comment]
> I don't think this would work. According to cibuildwheel documentation I created this special-purpose YAML file:
> [travis-extra.yml.zip](https://github.com/JorjMcKie/py-mupdf/files/6342271/travis-extra.yml.zip)

@JorjMcKie, Possibly I might be missing something, however with this change the aarch64 wheels are getting generated successfully. Could you please have a look at the [logs](https://travis-ci.com/github/odidev/py-mupdf/jobs/499786314) for my changes and share your feedback regarding this.

**Comment by JorjMcKie** [comment]
@odidev - did you check if the wheels work?
If yes, I am glad and happily accept those changes - but only as an extra YAML file, like the one I sent you.
I need to keep control of when I create normal desktop wheels and any others.
If this works, I am of willing to add aarch64 wheels on every version publication.

Anyway, thanks a lot for your efforts!

**Comment by odidev** [comment]
> @odidev - did you check if the wheels work?
I built the wheel using same steps on aarch64 machine and its working as expected. Below are the logs:
```
ubuntu@1pthunderx1-137:~/py-mupdf/wheelhouse$ uname -m
aarch64
ubuntu@1pthunderx1-137:~/py-mupdf/wheelhouse$
ubuntu@1pthunderx1-137:~/py-mupdf/wheelhouse$ ls
PyMuPDF-1.18.13-cp35-cp35m-manylinux2014_aarch64.whl  PyMuPDF-1.18.13-cp37-cp37m-manylinux2014_aarch64.whl  PyMuPDF-1.18.13-cp39-cp39-manylinux2014_aarch64.whl
PyMuPDF-1.18.13-cp36-cp36m-manylinux2014_aarch64.whl  PyMuPDF-1.18.13-cp38-cp38-manylinux2014_aarch64.whl
ubuntu@1pthunderx1-137:~/py-mupdf/wheelhouse$
ubuntu@1pthunderx1-137:~/py-mupdf/wheelhouse$ pip3 install PyMuPDF-1.18.13-cp38-cp38-manylinux2014_aarch64.whl
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://packagecloud.io/abeja/platform-public/pypi/simple
Processing ./PyMuPDF-1.18.13-cp38-cp38-manylinux2014_aarch64.whl
Installing collected packages: PyMuPDF
Successfully installed PyMuPDF-1.18.13
ubuntu@1pthunderx1-137:~/py-mupdf/wheelhouse$
ubuntu@1pthunderx1-137:~/py-mupdf/wheelhouse$
ubuntu@1pthunderx1-137:~/py-mupdf/wheelhouse$ python3.8
Python 3.8.0 (default, Jul 22 2020, 09:34:34)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyMuPDF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PyMuPDF'
>>> import fitz
>>> print(fitz.__doc__)

PyMuPDF 1.18.13: Python bindings for the MuPDF 1.18.0 library.
Version date: 2021-05-03 08:51:54.
Built for Python 3.8 on linux (64-bit).
```

> If yes, I am glad and happily accept those changes - but only as an extra YAML file, like the one I sent you.

I have pushed the changes as travis-extra.yml .

> If this works, I am of willing to add aarch64 wheels on every version publication.

As from the above logs we can see it is working as expected.

**Comment by JorjMcKie** [comment]
Thank you very much! Will integrate this in my next version publication.

**Comment by JorjMcKie** [comment]
@odidev - published version 1.18.13 today.
Based on your PR, I also created Linux ARM wheels which are uploaded to PyPI as well.
I hope they do work!
Thanks again for your help!

**Pull request merged**
